### PR TITLE
The NameGenerator Code is finished

### PR DESCRIPTION
**Pull request by VinzRulloda**
Can you please check and review my code if it meets the coding standard and if there are any errors

### CODE REVIEW

**Review by crshdgm — CHANGES_REQUESTED** [review]
The code does not follow coding standards and has errors in between the brackets.

**Review by crshdgm — APPROVED** [review]
Fixed

**Review by IanRetuta — APPROVED** [review]
Code approved.

**Comment by IanRetuta** [comment]
I've already merged the code to the main branch

**Pull request merged**
